---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Crowdsourced, for Fontello project
  github: https://github.com/fontello/brandico.font
  license: SIL
  license_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

transform:
  baseline: 0.5

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: brandico

  fullname: Brandico
  familyname: Brandico

  copyright: (C) 2012 by Vitaly Puzrin

  ascent: 800
  descent: 200


glyphs:

  - file: facebook
    code: 0xf300
    uid: 240979dd9fcf2e46250e66792edb8092
    css: facebook
    transform:
      offset: 0.05
    meta:
      author: Facebook
      homepage: http://www.facebook.com/brandpermissions/logos.php
    search: [facebook]

  - file: facebook-rect
    code: 0xf301
    uid: 8045477f6a7ef0bd7caff130ad25b88d
    css: facebook-rect
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [facebook]

  - file: twitter
    code: 0xf302
    uid: d611dd319d8c13b4551dc5bd85c1bdfd
    css: twitter
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [twitter]

  - file: twitter-bird
    code: 0xf303
    uid: 4c01f5d3ba5fbf029bca8630cce41e6a
    css: twitter-bird
    transform:
      rescale: 0.9
      offset: 0.05
    meta:
      author: Twitter
      homepage: https://twitter.com/about/resources/logos
    search: [twitter]

  - file: vimeo
    code: 0xf30f
    uid: 70cdf244c51630e09038659d1dcbee87
    css: vimeo
    transform:
      rescale: 0.8
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [vimeo]

  - file: vimeo-rect
    code: 0xf30e
    uid: 31483d870b3f14ac12bdfe7331a6af99
    css: vimeo-rect
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [vimeo]

  - file: tumblr
    code: 0xf311
    uid: 076f25da90f45dd112e006f2cd7ea76b
    css: tumblr
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [tumblr]

  - file: tumblr-rect
    code: 0xf310
    uid: 9e6a3483242474b6a1f77739ae3fdfdc
    css: tumblr-rect
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [tumblr]

  - file: googleplus-rect
    code: 0xf309
    uid: 626fb97a7c0c0db53a1853fb9e96e223
    css: googleplus-rect
    transform:
      offset: 0.05
    meta:
      author: Google
      homepage: http://www.google.com/+/business/brand-guidelines.html
    search: [google]

  - file: github-text
    code: 0xf307
    uid: 24d1008bf15b6c02a5e7a6af026987dd
    css: github-text
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [github]

  - file: github
    code: 0xf308
    uid: 4a0bb1ac004980bb3837560d4c9e8cee
    css: github
    transform:
      rescale: 0.9
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [github]

  - file: skype
    code: 0xf30b
    uid: 5a00c877da3f63d37cdc021815e3f5a9
    css: skype
    transform:
      offset: 0.05
    meta:
      author: Alex Peattie
      homepage: http://www.alexpeattie.com/projects/justvector_icons/
    search: [skype]

  - file: icq
    code: 0xf304
    uid: 01f67de2dc0137389f1c3aced6273acd
    css: icq
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [icq]



  - file: yandex
    code: 0xf305
    uid: b2417d1ce399577d53fff70d54976fea
    css: yandex
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [yandex]

  - file: yandex-rect
    code: 0xf306
    uid: ea0cb6bedac64ae7933b03dad3130ef6
    css: yandex-rect
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [yandex]

  - file: vkontakte-rect
    code: 0xf30a
    uid: 5b16ceef1c8638bd5389c9302ea04098
    css: vkontakte-rect
    transform:
      offset: 0.05
    meta:
      author: Vkontakte
      homepage: http://vk.com/help.php?page=about
    search: [vkontakte]

  - file: odnoklassniki
    code: 0xf30c
    uid: 229e50061df526f24f1ae884fab52101
    css: odnoklassniki
    transform:
      offset: 0.05
    meta:
      author: MailRu Group
      homepage: http://corp.mail.ru/communications/odnoklassniki
    search: [odnoklassniki]

  - file: odnoklassniki-rect
    code: 0xf30d
    uid: 4a02cc611ae9fb342d6026b2ed6cc44e
    css: odnoklassniki-rect
    transform:
      offset: 0.05
    meta:
      author: MailRu Group
      homepage: http://corp.mail.ru/communications/odnoklassniki
    search: [odnoklassniki]

  - file: friendfeed
    code: 0xf31a
    uid: eeec90e0e80f11e1aff10800200c9a66
    css: friendfeed
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [friendfeed]

  - file: friendfeed-rect
    code: 0xf31b
    uid: 41f4dd00e81111e1aff10800200c9a66
    css: friendfeed-rect
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [friendfeed]

  - file: blogger-rect
    code: 0xf31c
    uid: a38dfae0ec2d11e1aff10800200c9a66
    css: blogger-rect
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [blogger]

  - file: deviantart
    code: 0xf31d
    uid: d04790a0ec2d11e1aff10800200c9a66
    css: deviantart
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [deviantart]

  - file: deviantart-rect
    code: 0xf32a
    uid: e82e56e0ec2d11e1aff10800200c9a66
    css: deviantart
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [deviantart]

  - file: jabber
    code: 0xf32b
    uid: 466d1430ec2e11e1aff10800200c9a66
    css: jabber
    transform:
      offset: 0.05
    meta:
      author: Jabber Software Foundation
      homepage: http://xmpp.org
    search: [jabber]

  - file: lastfm
    code: 0xf32c
    uid: 9e237480ec2e11e1aff10800200c9a66
    css: lastfm
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [lastfm]

  - file: lastfm-rect
    code: 0xf32d
    uid: 53a3bbcda09740c98a1c3d2e0a6a89fb
    css: lastfm-rect
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [lastfm]

  - file: linkedin
    code: 0xf33a
    uid: 542e3f055aaa4ddfb9ab3e00397db47f
    css: linkedin
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [linkedin]

  - file: linkedin-rect
    code: 0xf33b
    uid: e9e96618b0f44170930f9b179237c76e
    css: linkedin-rect
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [linkedin]

  - file: picasa
    code: 0xf33c
    uid: d93230ef6fa54fb9805ba4cc9d9af5b1
    css: picasa
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [picasa]

  - file: picasa-rect
    code: 0xf33d
    uid: 6e4cba4a566942a9bf6c88b2caab74b5
    css: picasa-rect
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [picasa]

  - file: wordpress
    code: 0xf34a
    uid: 1357ba39f8dc4519949cc4da55226b62
    css: wordpress
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [wordpress]

  - file: wordpress-rect
    code: 0xf34b
    uid: 92b40fb51def4d1abae0dd841c7e1890
    css: wordpress-rect
    transform:
      offset: 0.05
    meta:
      author: Open Icon Library
      homepage: http://openiconlibrary.sourceforge.net
    search: [wordpress]
